### ISSUE TITLE
后台报错

### ISSUE THREAD

**Issue by XYZliang** [007gzs/meeting#16]
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:23:49 19018.139769576945408 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 128, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 103, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 138, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.6/dist-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/cool/views/view.py", line 283, in handle_exception
    return super().handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cool/views/view.py", line 245, in get
    return self.view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cool/views/view.py", line 241, in view
    context = self.get_context(request, *args, **kwargs)
  File "/home/ubuntu/meeting/apps/wechat/views.py", line 22, in get_context
    session = biz.wechat.wxa.code_to_session(request.params.js_code)
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/api/wxa.py", line 486, in code_to_session
    'grant_type': 'authorization_code'
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/api/base.py", line 14, in _get
    return self._client.get(url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/base.py", line 172, in get
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/base.py", line 77, in _request
    kwargs['params']['access_token'] = self.access_token
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/base.py", line 248, in access_token
    self.fetch_access_token()
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/__init__.py", line 65, in fetch_access_token
    'secret': self.secret
  File "/usr/local/lib/python3.6/dist-packages/wechatpy/client/base.py", line 218, in _fetch_access_token
    response=res
wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret, view more at http://t.cn/RAEkdVq rid: 60481fa5-38ba04e1-728a990c
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:29:16 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)
21/03/10 09:29:17 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/03/10 09:29:17 19018.139769565406976 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/03/10 09:29:17 19018.139769565406976 DEBUG utils.debug_sql (0.000) SELECT `wechat_user`.`id`, `wechat_user`.`create_time`, `wechat_user`.`modify_time`, `wechat_user`.`delete_status`, `wechat_user`.`remark`, `wechat_user`.`openid`, `wechat_user`.`unionid`, `wechat_user`.`session_key`, `wechat_user`.`nickname`, `wechat_user`.`gender`, `wechat_user`.`language`, `wechat_user`.`country`, `wechat_user`.`province`, `wechat_user`.`city`, `wechat_user`.`avatarurl`, `wechat_user`.`mobile` FROM `wechat_user` WHERE (NOT `wechat_user`.`delete_status` AND `wechat_user`.`id` IN (1)); args=(1,)

**Comment by XYZliang** [comment]
是服务器端需要更新appsecret
